[package]
name = "corfetch"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.26.1"
linked-hash-map = "0.5.6"
big-bytes = "1.0.0"
colored = "2.0.0"